language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

git:
    depth: 1

php:
    - 7.2
    - 7.3

before_install:
    - composer require php-coveralls/php-coveralls --prefer-dist --no-interaction --no-progress
    - composer global require localheinz/composer-normalize --prefer-dist --no-interaction --no-progress

install:
    - composer install --prefer-dist --no-interaction --no-progress
    - npm i

script:
    - mkdir -p build/logs
    - composer normalize --indent-size 4 --indent-style space --dry-run
    - php vendor/bin/php-cs-fixer fix --diff --config vendor/becklyn/php-cs/.php_cs.dist --dry-run --no-interaction
    - php vendor/bin/phpstan analyse -l 4 --memory-limit 4G --ansi -c vendor/becklyn/php-cs/phpstan_lib.neon . --no-interaction --no-progress
    - ./vendor/bin/simple-phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
    - npx kaba analyze
    - npm audit
    - npx prettier-package-json package.json --list-different --tab-width 4


after_script:
    - travis_retry php vendor/bin/php-coveralls
